from enum import IntEnum


class CanvasItemTextureFilter(IntEnum):
    TEXTURE_FILTER_PARENT_NODE = 0
    TEXTURE_FILTER_NEAREST = 1
    TEXTURE_FILTER_LINEAR = 2
    TEXTURE_FILTER_NEAREST_WITH_MIPMAPS = 3
    TEXTURE_FILTER_LINEAR_WITH_MIPMAPS = 4
    TEXTURE_FILTER_MAX = 5


class CanvasItemTextureRepeat(IntEnum):
    TEXTURE_REPEAT_PARENT_NODE = 0
    TEXTURE_REPEAT_DISABLED = 1
    TEXTURE_REPEAT_ENABLED = 2
    TEXTURE_REPEAT_MIRROR = 3
    TEXTURE_REPEAT_MAX = 4


class CanvasLightMode(IntEnum):
    LIGHT_MODE_POINT = 0
    LIGHT_MODE_DIRECTIONAL = 1


class CanvasLightBlendMode(IntEnum):
    LIGHT_BLEND_MODE_ADD = 0
    LIGHT_BLEND_MODE_SUB = 1
    LIGHT_BLEND_MODE_MIX = 2
